import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {loadSeed} from './seed';
import './styles.css';

const SEED=loadSeed();
const TODAY='2026-09-10';
const STORAGE='wings-master-v2-exact';
const CAPACITY=7;
const MAX_DAY_ITEMS=7;
const PRIORITY={Critical:60,High:40,Medium:25,Normal:10,Low:0};
const STATUS={not_done:'planned','Not Started':'planned','In Progress':'in_progress','Ongoing':'in_progress',blocked:'blocked',shipped:'shipped'};
const pretty=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const iso=d=>d?new Date(d+'T00:00:00'):null;
const fmtDate=d=>d?iso(d).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'Unscheduled';
const dayKey=d=>d.toISOString().slice(0,10);
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const workdays=(a,b)=>{if(!a||!b)return[];const out=[];for(let d=iso(a);d<=iso(b);d=addDays(d,1)){if(d.getDay()!==0&&d.getDay()!==6)out.push(dayKey(d))}return out};
function normalizeSeed(){
  const projects=SEED.projects.map(p=>({...p}));
  const tasks=SEED.tasks.map(t=>({...t,status:STATUS[t.status]||String(t.status||'planned').toLowerCase().replace(/\s+/g,'_'),priority:t.priority==='Medium'?'Medium':t.priority||'Normal'}));
  const subtasks=SEED.subtasks.map(s=>({...s,status:'planned',priority:'Normal',effort:1,carryForward:0,completedDate:null}));
  const scheduled={};
  tasks.forEach(t=>{const ids=subtasks.filter(s=>s.taskId===t.id).map(s=>s.id);const days=workdays(t.startDate,t.eta);if(days.length&&ids.length)ids.forEach((id,i)=>scheduled[id]=days[Math.min(days.length-1,Math.floor(i*days.length/ids.length))]);});
  return {projects,tasks,subtasks:subtasks.map(s=>({...s,scheduledDate:scheduled[s.id]||null}))};
}
function initial(){try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw);if(parsed?.schema==='wings-v2-exact'&&parsed.projects?.length===8&&parsed.tasks?.length===48&&parsed.subtasks?.length===201)return parsed;}}catch{}return {...normalizeSeed(),schema:'wings-v2-exact'}}
function enrich(data){const p=Object.fromEntries(data.projects.map(x=>[x.id,x]));const t=Object.fromEntries(data.tasks.map(x=>[x.id,x]));return data.subtasks.map(s=>({...s,task:t[s.taskId],project:p[t[s.taskId]?.projectId]}))}
function scoreSub(s,today){const t=s.task||{};let score=0;if(s.scheduledDate===today)score+=100;if(s.scheduledDate&&s.scheduledDate<today)score+=70;score+=PRIORITY[s.priority]||10;score+=t.status==='in_progress'?35:0;score+=t.eta&&t.eta>=today&&t.eta<=dayKey(addDays(iso(today),3))?30:0;score+=t.projectId==='PRJ-03'?20:0;score+=Number(s.carryForward||0)*80;return score}
function makePlan(items,today){const candidates=items.filter(s=>s.status!=='shipped'&&(s.scheduledDate===today||!s.scheduledDate||s.scheduledDate<today));const ranked=[...candidates].sort((a,b)=>scoreSub(b,today)-scoreSub(a,today));const selected=[];let hours=0;for(const s of ranked){const e=Number(s.effort||1);if(selected.length>=MAX_DAY_ITEMS||hours+e>CAPACITY)continue;selected.push(s);hours+=e}return{selected,plannedHours:hours,candidateCount:candidates.length,rationale:'Sprint intent + carry-forward + priority + current reality'}}
function App(){
 const [data,setData]=useState(initial);const [view,setView]=useState('Day');const [selected,setSelected]=useState(null);const [search,setSearch]=useState('');const [toast,setToast]=useState('');const [addOpen,setAddOpen]=useState(false);const [addContext,setAddContext]=useState({});
 useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(data)),[data]);
 const items=useMemo(()=>enrich(data),[data]);const taskBy=useMemo(()=>Object.fromEntries(data.tasks.map(t=>[t.id,t])),[data.tasks]);const plan=useMemo(()=>makePlan(items,TODAY),[items]);
 const flash=m=>{setToast(m);setTimeout(()=>setToast(''),1300)};
 const updateSub=(id,patch)=>{setData(d=>({...d,subtasks:d.subtasks.map(s=>s.id===id?{...s,...patch}:s)}));setSelected(x=>x&&x.id===id?{...x,...patch}:x);flash('Saved')};
 const updateTask=(id,patch)=>{setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,...patch}:t)}));flash('Saved')};
 const addWork=payload=>{setData(d=>{if(payload.type==='Project'){const id='PRJ-'+String(Date.now()).slice(-6);return{...d,projects:[...d.projects,{id,name:payload.title,description:payload.description||'',status:'Not Started',portfolio:'Core',startDate:null,endDate:null,tag:''}]}}if(payload.type==='Task'){const id='WNG-T-'+String(Date.now()).slice(-7);return{...d,tasks:[...d.tasks,{id,projectId:payload.projectId,title:payload.title,description:payload.description||'',status:'planned',priority:payload.priority||'Normal',eta:null,plannedWeek:'',actualEndDate:null,spillover:false,personal:false}]}}const id='WNG-S-'+String(Date.now()).slice(-7);return{...d,subtasks:[...d.subtasks,{id,taskId:payload.taskId,projectId:taskBy[payload.taskId]?.projectId,title:payload.title,description:payload.description||'',status:'planned',priority:payload.priority||'Normal',scheduledDate:payload.scheduledDate||TODAY,effort:Number(payload.effort||1),carryForward:0,completedDate:null}]}});setAddOpen(false);flash('Added to Master Data')};
 const reset=()=>{localStorage.removeItem(STORAGE);location.reload()};
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="mark">W</span><span>Wings</span></div><nav>{['Day','Week','Sprint','Master Data','Insights'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</nav><div className="side-bottom"><div className="capacity-card"><span>September Sprint</span><strong>90h</strong><small>feasible capacity</small></div><button className="reset" onClick={reset}>Reset to source data</button></div></aside><main><header className="topbar"><div><h1>{view==='Day'?'FDE Collection':view}</h1>{view==='Day'&&<div className="subhead">Today · 10 Sep 2026</div>}</div><div className="top-actions"><div className="date-chip"><span>Today</span><strong>10 Sep</strong></div>{view!=='Day'&&<button className="add-link" onClick={()=>{setAddContext({});setAddOpen(true)}}>+ Add work</button>}</div></header>{view==='Day'&&<DayView items={items} plan={plan} setSelected={setSelected} updateSub={updateSub} openAdd={()=>{setAddContext({type:'Subtask',scheduledDate:TODAY});setAddOpen(true)}}/>}{view==='Week'&&<WeekView items={items} today={TODAY} setSelected={setSelected}/>} {view==='Sprint'&&<SprintView data={data} items={items} setSelected={setSelected}/>} {view==='Master Data'&&<MasterView data={data} items={items} search={search} setSearch={setSearch} setSelected={setSelected} updateTask={updateTask} openAdd={ctx=>{setAddContext(ctx);setAddOpen(true)}}/>}{view==='Insights'&&<Insights data={data} items={items}/>}</main>{selected&&<Drawer item={selected} close={()=>setSelected(null)} updateSub={updateSub}/>} {addOpen&&<AddDrawer data={data} context={addContext} close={()=>setAddOpen(false)} addWork={addWork}/>} {toast&&<div className="toast">{toast}</div>}</div>}
function DayView({items,plan,setSelected,updateSub,openAdd}){const plannedIds=new Set(plan.selected.map(s=>s.id));const backlog=[...items].filter(s=>!plannedIds.has(s.id)&&s.status!=='shipped'&&(!s.scheduledDate||s.scheduledDate>TODAY)).sort((a,b)=>scoreSub(b,TODAY)-scoreSub(a,TODAY)).slice(0,8);const progress=items.filter(s=>s.status==='in_progress').slice(0,8);const shipped=items.filter(s=>s.status==='shipped'&&s.completedDate===TODAY);return <section><div className="day-intro"><div><div className="eyebrow">In focus today</div><h2>FDE Collection</h2><p>{plan.selected.length} work items selected. The plan stays within the 7h working limit.</p></div><button className="secondary" onClick={openAdd}>+ Add subtask</button></div><div className="plan-strip"><div><strong>Planning agent</strong><span>Prioritizing sprint intent, carry-forward, priority, dates and current progress.</span></div><button>Why this plan</button></div><div className="kanban">{[['Backlog',backlog],['Planned',plan.selected],['In progress',progress],['Shipped',shipped]].map(([name,list])=><Lane key={name} name={name} items={list} setSelected={setSelected} updateSub={updateSub}/>)}</div></section>}
function Lane({name,items,setSelected,updateSub}){return <div className="lane"><div className="lane-head"><span>{name}</span><b>{items.length}</b></div>{items.map(s=><Card key={s.id} s={s} setSelected={setSelected} updateSub={updateSub}/>)}{!items.length&&<div className="empty">Nothing here</div>}</div>}
function Card({s,setSelected,updateSub}){return <article className={'card '+(s.status==='blocked'?'is-blocked':'')} onClick={()=>setSelected(s)}><div className="card-meta"><span className={'priority p-'+String(s.priority||'Normal').toLowerCase()}>{s.priority||'Normal'}</span><span>{fmtDate(s.scheduledDate)}</span></div><h3>{s.title}</h3><p>{s.project?.name} · {s.task?.title}</p><div className="card-bottom"><span>{Number(s.effort||1).toFixed(1)}h</span><select value={pretty(s.status)} onClick={e=>e.stopPropagation()} onChange={e=>{e.stopPropagation();const v=e.target.value;updateSub(s.id,{status:v==='Shipped'?'shipped':v==='Blocked'?'blocked':v==='In Progress'?'in_progress':'planned',completedDate:v==='Shipped'?TODAY:null})}}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></div></article>}
function WeekView({items,today,setSelected}){const [offset,setOffset]=useState(0);const base=addDays(iso(today),-((iso(today).getDay()+6)%7)+offset*7);const days=Array.from({length:5},(_,i)=>addDays(base,i));const label=`${days[0].toLocaleDateString('en-IN',{day:'numeric',month:'short'})} - ${days[4].toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}`;return <section><div className="section-head"><div><div className="eyebrow">Week</div><h2>{label}</h2></div><div className="week-controls"><button onClick={()=>setOffset(x=>x-1)}>‹</button><button onClick={()=>setOffset(0)}>This week</button><button onClick={()=>setOffset(x=>x+1)}>›</button></div></div><div className="week-board">{days.map(d=>{const date=dayKey(d);const mode=date<today?'Snapshot':date===today?'Today':'Plan';const dayItems=items.filter(s=>s.scheduledDate===date&&s.status!=='shipped');const shipped=items.filter(s=>s.status==='shipped'&&s.completedDate===date);return <div className={'week-day '+(date===today?'current':'')} key={date}><div className="week-day-head"><div><strong>{d.toLocaleDateString('en-IN',{weekday:'short'})}</strong><span>{fmtDate(date)}</span></div><em>{mode}</em></div><div className="week-section"><label>Planned</label>{dayItems.filter(s=>s.status!=='in_progress').slice(0,8).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div><div className="week-section"><label>In progress</label>{dayItems.filter(s=>s.status==='in_progress').slice(0,8).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div><div className="week-section shipped"><label>Shipped {shipped.length?`· ${shipped.length}`:''}</label>{shipped.slice(0,8).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div>{!dayItems.length&&!shipped.length&&<div className="empty small">No planned work</div>}</div>})}</div><p className="history-note">Past days are designed to read from immutable EOD snapshots. Until snapshots exist, historical columns are clearly marked rather than pretending current state is history.</p></section>}
function Mini({s,setSelected}){return <button className="mini" onClick={()=>setSelected(s)}><span className={'dot '+s.status}></span><span>{s.title}</span><small>{s.task?.id}</small></button>}
function SprintView({data,items,setSelected}){const total=data.subtasks.length,done=items.filter(s=>s.status==='shipped').length;const tasks=data.tasks.filter(t=>t.startDate&&t.eta);const start=iso('2026-09-01'),end=iso('2026-09-30'),span=(end-start)+86400000;return <section><div className="sprint-summary"><div><div className="eyebrow">September Sprint</div><h2>90h feasible capacity</h2><p>18 working days · 18h buffer · max 7 subtasks per day</p></div><div className="sprint-kpis"><div><strong>{done}/{total}</strong><span>subtasks shipped</span></div><div><strong>{Math.round(done/Math.max(total,1)*100)}%</strong><span>closure</span></div></div></div><div className="sprint-toolbar"><strong>Sprint timeline</strong><span>Task-level Gantt · September</span></div><div className="gantt"><div className="gantt-head"><div>Task</div><div className="timeline-head">{Array.from({length:30},(_,i)=><span key={i}>{i+1}</span>)}</div></div>{tasks.map(t=>{const left=((iso(t.startDate)-start)/span)*100,width=Math.max(1,((iso(t.eta)-iso(t.startDate)+86400000)/span)*100);return <button className="gantt-row" key={t.id} onClick={()=>{const s=items.find(x=>x.task?.id===t.id);if(s)setSelected(s)}}><div><strong>{t.id}</strong><span>{t.title}</span></div><div className="timeline"><i style={{left:left+'%',width:width+'%'}}></i></div></button>})}</div><div className="project-summary">{data.projects.map(p=>{const ss=items.filter(s=>s.project?.id===p.id),d=ss.filter(s=>s.status==='shipped').length;return <div key={p.id}><span>{p.name}</span><strong>{d}/{ss.length}</strong></div>})}</div></section>}
function MasterView({data,search,setSearch,setSelected,openAdd}){const [openProjects,setOpenProjects]=useState({}),[openTasks,setOpenTasks]=useState({});const q=search.trim().toLowerCase();const matches=x=>!q||[x.title,x.description,x.name].some(v=>String(v||'').toLowerCase().includes(q));return <section><div className="section-head"><div><div className="eyebrow">Source of truth</div><h2>Master Data</h2></div><div className="master-count">8 projects · 48 tasks · 201 subtasks</div></div><div className="master-tools"><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, tasks, subtasks"/></div><div className="add-group"><button onClick={()=>openAdd({type:'Project'})}>+ Project</button><button onClick={()=>openAdd({type:'Task'})}>+ Task</button><button onClick={()=>openAdd({type:'Subtask'})}>+ Subtask</button></div></div><div className="master-table"><div className="master-header"><span>Project</span><span>Task</span><span>Subtask</span><span>Status</span><span>Priority</span><span>Plan for</span><span>Details</span></div>{data.projects.map(p=>{const ts=data.tasks.filter(t=>t.projectId===p.id);const projectMatch=matches(p)||ts.some(t=>matches(t)||data.subtasks.some(s=>s.taskId===t.id&&matches(s)));if(q&&!projectMatch)return null;const po=!!openProjects[p.id]||!!q;return <div key={p.id}><button className="master-row project" onClick={()=>setOpenProjects(x=>({...x,[p.id]:!x[p.id]}))}><span><b>{po?'▾':'▸'}</b>{p.name}</span><span></span><span></span><span>{p.status}</span><span>-</span><span>{p.startDate?`${fmtDate(p.startDate)} - ${fmtDate(p.endDate)}`:'Flexible'}</span><span>{p.description}</span></button>{po&&ts.map(t=>{const ss=data.subtasks.filter(s=>s.taskId===t.id);if(q&&!matches(t)&&!ss.some(matches))return null;const to=!!openTasks[t.id]||!!q;return <div key={t.id}><button className="master-row task" onClick={()=>setOpenTasks(x=>({...x,[t.id]:!x[t.id]}))}><span></span><span><b>{to?'▾':'▸'}</b>{t.id} · {t.title}</span><span></span><span>{pretty(t.status)}</span><span>{t.priority}</span><span>{t.plannedWeek||'Flexible'}</span><span>{t.description}</span></button>{to&&ss.map(s=><button className="master-row subtask" key={s.id} onClick={()=>setSelected({...s,task:t,project:p})}><span></span><span></span><span><b>{s.id}</b> · {s.title}</span><span>{pretty(s.status)}</span><span>{s.priority}</span><span>{fmtDate(s.scheduledDate)}</span><span>{s.description}</span></button>)}</div>})}</div>})}</div></section>}
function Insights({items}){const shipped=items.filter(s=>s.status==='shipped').length,blocked=items.filter(s=>s.status==='blocked').length,carry=items.filter(s=>Number(s.carryForward)>0).length;return <section><div className="section-head"><div><div className="eyebrow">Patterns, not BI</div><h2>Insights</h2></div></div><div className="insight-grid"><Metric label="Closure rate" value={`${Math.round(shipped/Math.max(items.length,1)*100)}%`} note="subtasks shipped"/><Metric label="Carry-forward" value={carry} note="items carried"/><Metric label="Blocked" value={blocked} note="items blocked"/><Metric label="Open work" value={items.length-shipped} note="subtasks remaining"/></div><div className="insight-panel"><h3>What Wings should learn</h3><p>Compare planned dates with actual completion, surface repeated carry-forward, and measure remaining work against remaining Sprint capacity. The goal is to reveal your working system, not create another BI dashboard.</p></div></section>}
function Metric({label,value,note}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Drawer({item,close,updateSub}){return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">Subtask</div><h2>{item.title}</h2><p className="muted">{item.task?.title||item.taskId}</p><Field label="Summary"><textarea defaultValue={item.description||''} onBlur={e=>updateSub(item.id,{description:e.target.value})}/></Field><div className="drawer-grid"><Field label="Status"><select value={pretty(item.status)} onChange={e=>updateSub(item.id,{status:e.target.value==='Shipped'?'shipped':e.target.value==='Blocked'?'blocked':e.target.value==='In Progress'?'in_progress':'planned',completedDate:e.target.value==='Shipped'?TODAY:null})}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></Field><Field label="Priority"><select value={item.priority||'Normal'} onChange={e=>updateSub(item.id,{priority:e.target.value})}><option>Critical</option><option>High</option><option>Medium</option><option>Normal</option><option>Low</option></select></Field><Field label="Planned date"><input type="date" value={item.scheduledDate||''} onChange={e=>updateSub(item.id,{scheduledDate:e.target.value||null})}/></Field><Field label="Effort"><input type="number" min=".25" step=".25" value={item.effort||1} onChange={e=>updateSub(item.id,{effort:Number(e.target.value)})}/></Field></div><div className="drawer-meta"><span>Task</span><strong>{item.task?.id||item.taskId}</strong><span>Project</span><strong>{item.project?.name||''}</strong></div></aside></div>}
function Field({label,children}){return <div className="field"><label>{label}</label>{children}</div>}
function AddDrawer({data,context,close,addWork}){const [type,setType]=useState(context.type||'Subtask'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[projectId,setProjectId]=useState(context.projectId||data.projects[0]?.id||''),[taskId,setTaskId]=useState(context.taskId||data.tasks[0]?.id||''),[priority,setPriority]=useState('Normal'),[date,setDate]=useState(context.scheduledDate||TODAY),[effort,setEffort]=useState('1');const tasks=data.tasks.filter(t=>t.projectId===projectId);useEffect(()=>{if(type==='Task'&&tasks[0]&&!tasks.some(t=>t.id===taskId))setTaskId(tasks[0].id)},[projectId,type]);const submit=()=>{if(!title.trim())return;addWork({type,title:title.trim(),description,projectId,taskId,priority,scheduledDate:date,effort})};return <div className="drawer-backdrop" onClick={close}><aside className="drawer add-drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">Add work</div><h2>Keep it simple.</h2><p className="muted">Wings fills the rest from context. No browser pop-ups.</p><div className="segmented">{['Project','Task','Subtask'].map(x=><button key={x} className={type===x?'active':''} onClick={()=>setType(x)}>{x}</button>)}</div><Field label="What do you want to add?"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='Project'?'Project name':type==='Task'?'Task name':'Subtask name'}/></Field>{type!=='Project'&&<Field label={type==='Task'?'Project':'Task'}><select value={type==='Task'?projectId:taskId} onChange={e=>type==='Task'?setProjectId(e.target.value):setTaskId(e.target.value)}>{(type==='Task'?data.projects:tasks).map(x=><option key={x.id} value={x.id}>{type==='Task'?x.name:x.id+' · '+x.title}</option>)}</select></Field>}{type==='Subtask'&&<Field label="Planned date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field>}{type!=='Project'&&<Field label="Priority"><select value={priority} onChange={e=>setPriority(e.target.value)}><option>Critical</option><option>High</option><option>Medium</option><option>Normal</option><option>Low</option></select></Field>}{type==='Subtask'&&<Field label="Effort"><input type="number" min=".25" step=".25" value={effort} onChange={e=>setEffort(e.target.value)}/></Field>}<Field label="Optional description"><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add only if useful"/></Field><button className="primary full" onClick={submit}>Add {type}</button></aside></div>}
createRoot(document.getElementById('root')).render(<App/>);
