import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { loadSeed } from './seed';
import './styles.css';

const RAW = loadSeed();
const CAPACITY = 7;
const MAX_DAY_ITEMS = 7;
const STORE = 'wings-master-v3-canonical';
const STATUS = { 'Not Started':'planned', 'In Progress':'in_progress', 'Ongoing':'in_progress', 'not done':'planned', 'blocked':'blocked', 'shipped':'shipped' };
const PRIORITY = { Critical:60, High:40, Medium:25, Normal:10, Low:0 };
const pad = n => String(n).padStart(2,'0');
const key = d => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const date = s => s ? new Date(`${s}T00:00:00`) : null;
const addDays = (d,n) => { const x=new Date(d); x.setDate(x.getDate()+n); return x; };
const fmt = s => s ? date(s).toLocaleDateString('en-IN',{day:'numeric',month:'short'}) : 'Unscheduled';
const fmtLong = s => s ? date(s).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}) : 'Unscheduled';
const workdays = (a,b) => { if(!a||!b)return[]; const out=[]; for(let d=date(a); d<=date(b); d=addDays(d,1)) if(d.getDay()!==0&&d.getDay()!==6) out.push(key(d)); return out; };
const normalizeStatus = s => STATUS[s] || String(s||'planned').toLowerCase().replace(/\s+/g,'_');
const pretty = s => String(s||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const unique = (arr, field='id') => { const seen=new Set(); return arr.filter(x=>{const v=x?.[field]; if(!v||seen.has(v)) return false; seen.add(v); return true;}); };
const TASK_WINDOWS = {
  'SIN-103':['2026-09-02','2026-09-04'],'SIN-105':['2026-09-03','2026-09-04'],
  'BUG-201':['2026-09-02','2026-09-02'],'BUG-202':['2026-09-02','2026-09-02'],'BUG-203':['2026-09-02','2026-09-02'],'BUG-204':['2026-09-02','2026-09-02'],
  'BUG-205':['2026-09-02','2026-09-03'],'BUG-206':['2026-09-02','2026-09-03'],
  'COL-301':['2026-09-01','2026-09-04'],'COL-302':['2026-09-03','2026-09-08'],'COL-303':['2026-09-07','2026-09-18'],
  'COL-304':['2026-09-14','2026-09-23'],'COL-305':['2026-09-21','2026-09-25'],'COL-306':['2026-09-24','2026-09-29'],
  'COL-307':['2026-09-28','2026-10-09'],'COL-308':['2026-10-05','2026-10-16'],
  'SHELL-401':['2026-09-02','2026-09-02'],'SHELL-402':['2026-09-02','2026-09-02'],'SHELL-403':['2026-09-02','2026-09-02'],
  'SHELL-404':['2026-09-02','2026-09-02'],'SHELL-405':['2026-09-02','2026-09-02'],'SHELL-406':['2026-09-02','2026-09-02'],
  'PERF-501':['2026-09-03','2026-09-03'],'PERF-502':['2026-09-04','2026-09-04'],'PERF-503':['2026-09-07','2026-09-07'],
  'PERF-504':['2026-09-08','2026-09-08'],'PERF-505':['2026-09-09','2026-09-09'],'PERF-506':['2026-09-09','2026-09-09'],
  'JIRA-601':['2026-09-02','2026-09-02'],'JIRA-602':['2026-09-02','2026-09-02'],'JIRA-603':['2026-09-02','2026-09-02'],
  'JIRA-604':['2026-09-02','2026-09-02'],'JIRA-605':['2026-09-02','2026-09-02'],'SDHI-801':['2026-09-02','2026-09-02']
};
function inferEffort(title=''){const t=title.toLowerCase();if(/review|read|check|verify|inspect|look/.test(t))return .5;if(/collect|gather|inventory|kickoff|walk/.test(t))return .75;if(/document|capture|compare|identify|audit|consolidate/.test(t))return 1;if(/define|map|coordinate|prioritize|plan|requirement|guideline|prepare/.test(t))return 1.25;if(/synthesize|package|finalize|publish|sign-off|handoff/.test(t))return 1.5;if(/design|create|build|test|develop|record|video|deck/.test(t))return 2;return 1;}
function buildInitial(){
  const projects=unique((RAW.projects||[]).map(p=>({...p,portfolio:p.portfolio||(/Design Hub/i.test(p.name)?'DHI':'Core')})));
  const tasks=unique((RAW.tasks||[]).map(t=>({...t,status:normalizeStatus(t.status),priority:t.priority||'Normal'})));
  const validTaskIds=new Set(tasks.map(t=>t.id));
  const subtasks=unique((RAW.subtasks||[]).filter(s=>validTaskIds.has(s.taskId)).map(s=>({...s,status:normalizeStatus(s.sourceStatus||s.status),priority:s.priority||'Normal',effort:Number(s.effort)||inferEffort(s.title),carryForward:Number(s.carryForward)||0,completedDate:s.completedDate||null})));
  const scheduled={};
  Object.entries(TASK_WINDOWS).forEach(([tid,win])=>{const ids=subtasks.filter(s=>s.taskId===tid).map(s=>s.id);const days=workdays(win[0],win[1]);ids.forEach((id,i)=>{scheduled[id]=days.length?days[Math.min(days.length-1,Math.floor(i*days.length/ids.length))]:null;});});
  subtasks.forEach(s=>{if(!(s.id in scheduled))scheduled[s.id]=null;});
  return {schema:'wings-v3-canonical',projects,tasks,subtasks:subtasks.map(s=>({...s,scheduledDate:scheduled[s.id]}))};
}
function loadState(){try{const raw=localStorage.getItem(STORE);if(raw){const x=JSON.parse(raw);if(x.schema==='wings-v3-canonical'&&x.projects?.length===8&&x.tasks?.length===48&&x.subtasks?.length===201)return x;}}catch{}return buildInitial();}
function enrich(data){const p=Object.fromEntries(data.projects.map(x=>[x.id,x]));const t=Object.fromEntries(data.tasks.map(x=>[x.id,x]));return data.subtasks.map(s=>({...s,task:t[s.taskId],project:p[s.projectId||t[s.taskId]?.projectId]}));}
function score(s,today){const t=s.task||{};let n=0;if(s.scheduledDate===today)n+=100;if(s.scheduledDate&&s.scheduledDate<today)n+=70;n+=PRIORITY[s.priority]||10;n+=t.status==='in_progress'?35:0;n+=t.eta&&t.eta>=today&&t.eta<=key(addDays(date(today),3))?30:0;n+=Number(s.carryForward||0)*80;n+=t.projectId==='PRJ-03'?20:0;return n;}
function makePlan(items,today){const candidates=items.filter(s=>s.status!=='shipped'&&(s.scheduledDate===today||(s.scheduledDate&&s.scheduledDate<today)));const ranked=[...candidates].sort((a,b)=>score(b,today)-score(a,today)||String(a.id).localeCompare(String(b.id)));const selected=[];let hours=0;for(const s of ranked){const e=Number(s.effort)||1;if(selected.length>=MAX_DAY_ITEMS)break;if(hours+e<=CAPACITY){selected.push(s);hours+=e;}}return{selected,plannedHours:hours,candidateCount:candidates.length,rationale:'Sprint intent + carry-forward + priority + current reality'};}
function App(){
 const [data,setData]=useState(loadState);const [view,setView]=useState('Day');const [selected,setSelected]=useState(null);const [search,setSearch]=useState('');const [add,setAdd]=useState(null);const [agent,setAgent]=useState(false);const [toast,setToast]=useState('');const today=key(new Date());
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify(data)),[data]);const items=useMemo(()=>enrich(data),[data]);const plan=useMemo(()=>makePlan(items,today),[items,today]);const flash=m=>{setToast(m);setTimeout(()=>setToast(''),1200)};
 const updateSub=(id,patch)=>{setData(d=>({...d,subtasks:d.subtasks.map(s=>s.id===id?{...s,...patch}:s)}));setSelected(x=>x&&x.id===id?{...x,...patch}:x);flash('Saved');};
 const addWork=p=>{setData(d=>{if(p.type==='Project')return{...d,projects:[...d.projects,{id:`PRJ-${Date.now()}`,name:p.title,description:p.description||'',status:'Not Started',portfolio:'Core',startDate:null,endDate:null,tag:''}]};if(p.type==='Task')return{...d,tasks:[...d.tasks,{id:`WNG-T-${Date.now()}`,projectId:p.projectId,title:p.title,description:p.description||'',status:'planned',priority:p.priority||'Normal',eta:null,plannedWeek:'',actualEndDate:null,spillover:false,personal:false}]};const task=d.tasks.find(t=>t.id===p.taskId);return{...d,subtasks:[...d.subtasks,{id:`WNG-S-${Date.now()}`,taskId:p.taskId,projectId:task?.projectId,title:p.title,description:p.description||'',status:'planned',priority:p.priority||'Normal',scheduledDate:p.scheduledDate||null,effort:Number(p.effort)||1,carryForward:0,completedDate:null}]};});setAdd(null);flash('Added');};
 const reset=()=>{localStorage.removeItem(STORE);location.reload()};
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="mark">W</span><span>Wings</span></div><nav>{['Day','Week','Sprint','Master Data','Insights'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</nav><div className="side-bottom"><div className="capacity-card"><span>September Sprint</span><strong>90h</strong><small>feasible capacity · 18h buffer</small></div><button className="reset" onClick={reset}>Reset source data</button></div></aside><main><header className="topbar"><div><h1>{view==='Day'?'FDE Collection':view}</h1>{view==='Day'&&<div className="subhead">{fmtLong(today)}</div>}</div><div className="date-chip"><span>Today</span><strong>{fmt(today)}</strong></div></header>{view==='Day'&&<DayView items={items} plan={plan} today={today} setSelected={setSelected} updateSub={updateSub} agent={agent} setAgent={setAgent} openAdd={()=>setAdd({type:'Subtask',scheduledDate:today})}/>} {view==='Week'&&<WeekView items={items} today={today} setSelected={setSelected}/>} {view==='Sprint'&&<SprintView data={data} items={items} setSelected={setSelected}/>} {view==='Master Data'&&<MasterView data={data} items={items} search={search} setSearch={setSearch} setSelected={setSelected} openAdd={setAdd}/>} {view==='Insights'&&<Insights data={data} items={items}/>}</main>{selected&&<Drawer item={selected} today={today} close={()=>setSelected(null)} updateSub={updateSub}/>} {add&&<AddDrawer data={data} context={add} close={()=>setAdd(null)} addWork={addWork}/>} {toast&&<div className="toast">{toast}</div>}</div>;
}
function DayView({items,plan,today,setSelected,updateSub,agent,setAgent,openAdd}){const ids=new Set(plan.selected.map(s=>s.id));const backlog=items.filter(s=>!ids.has(s.id)&&s.status!=='shipped'&&s.scheduledDate&&s.scheduledDate>today).sort((a,b)=>score(b,today)-score(a,today)).slice(0,7);const progress=items.filter(s=>s.status==='in_progress'||s.status==='blocked').sort((a,b)=>score(b,today)-score(a,today)).slice(0,7);const shipped=items.filter(s=>s.status==='shipped'&&s.completedDate===today);return <section className="day"><div className="day-heading"><div><div className="eyebrow">In focus today</div><h2>FDE Collection</h2></div><button className="secondary" onClick={openAdd}>Add subtask</button></div><div className="agent-wrap"><button className="agent-badge" onClick={()=>setAgent(!agent)}><span className="agent-dot"></span>Planning agent <span>{agent?'−':'i'}</span></button>{agent&&<div className="agent-popover"><strong>Why this plan</strong><p>Wings ranks sprint intent, carry-forward, overdue work, priority, in-progress work and near-term risk, then applies the 7h and 7-subtask hard limits.</p></div>}</div><div className="kanban">{[['Backlog',backlog],['Planned',plan.selected],['In progress',progress],['Shipped',shipped]].map(([n,list])=><Lane key={n} name={n} items={list} setSelected={setSelected} updateSub={updateSub} today={today}/>)}</div></section>}
function Lane({name,items,setSelected,updateSub,today}){return <div className="lane"><div className="lane-head"><span>{name}</span><b>{items.length}</b></div>{items.map(s=><Card key={s.id} s={s} setSelected={setSelected} updateSub={updateSub} today={today}/>)}{!items.length&&<div className="empty">Nothing here</div>}</div>}
function Card({s,setSelected,updateSub,today}){const blocked=s.status==='blocked';const setStatus=v=>updateSub(s.id,{status:v==='Shipped'?'shipped':v==='Blocked'?'blocked':v==='In Progress'?'in_progress':'planned',completedDate:v==='Shipped'?today:null});return <article className={`card ${blocked?'is-blocked':''}`} onClick={()=>setSelected(s)}><div className="card-meta"><span className={`priority p-${String(s.priority||'Normal').toLowerCase()}`}>{s.priority||'Normal'}</span><span>{fmt(s.scheduledDate)}</span></div><h3>{s.title}</h3><p>{s.project?.name} · {s.task?.id}</p><div className="card-bottom"><span>{Number(s.effort||1).toFixed(1)}h</span><select value={pretty(s.status)} onClick={e=>e.stopPropagation()} onChange={e=>{e.stopPropagation();setStatus(e.target.value)}}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></div></article>}
function WeekView({items,today,setSelected}){const startOfWeek=d=>addDays(date(d),-((date(d).getDay()+6)%7));const [offset,setOffset]=useState(0);const [weekStart,setWeekStart]=useState(()=>key(startOfWeek(today)));useEffect(()=>setWeekStart(key(addDays(startOfWeek(today),offset*7))),[offset,today]);const days=Array.from({length:5},(_,i)=>addDays(date(weekStart),i));const label=`${days[0].toLocaleDateString('en-IN',{day:'numeric',month:'short'})} - ${days[4].toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}`;return <section><div className="section-head"><div><div className="eyebrow">Week</div><h2>{label}</h2></div><div className="week-controls"><button onClick={()=>setOffset(x=>x-1)}>‹</button><button onClick={()=>setOffset(0)}>This week</button><button onClick={()=>setOffset(x=>x+1)}>›</button></div></div><div className="week-grid">{days.map(d=>{const k=key(d);const mode=k<today?'Past':k===today?'Today':'Plan';const dayItems=items.filter(s=>s.scheduledDate===k&&s.status!=='shipped');const shipped=items.filter(s=>s.status==='shipped'&&s.completedDate===k);return <div className={`week-day ${k===today?'current':''}`} key={k}><div className="week-day-head"><div><strong>{d.toLocaleDateString('en-IN',{weekday:'short'})}</strong><span>{fmt(k)}</span></div><em>{mode}</em></div><div className="week-section"><label>Planned</label>{dayItems.filter(s=>s.status==='planned').slice(0,10).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div><div className="week-section"><label>In progress</label>{dayItems.filter(s=>s.status==='in_progress'||s.status==='blocked').slice(0,10).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div><div className="week-section shipped"><label>Shipped {shipped.length?`· ${shipped.length}`:''}</label>{shipped.slice(0,10).map(s=><Mini key={s.id} s={s} setSelected={setSelected}/>)}</div>{!dayItems.length&&!shipped.length&&<div className="empty small">No scheduled work</div>}</div>})}</div><div className="week-foot">Past days are historical views in the architecture. Future days show the current planned state. The EOD snapshot job belongs on the production database layer.</div></section>}
function Mini({s,setSelected}){return <button className="mini" onClick={()=>setSelected(s)}><span className={`dot ${s.status}`}></span><span>{s.title}</span><small>{s.task?.id}</small></button>}
function SprintView({data,items,setSelected}){const start=date('2026-09-01'),end=date('2026-09-30'),span=end-start+86400000;const tasks=data.tasks.filter(t=>TASK_WINDOWS[t.id]).map(t=>({...t,startDate:t.startDate||TASK_WINDOWS[t.id][0],eta:t.eta||TASK_WINDOWS[t.id][1]}));const done=items.filter(s=>s.status==='shipped').length;return <section><div className="sprint-summary"><div><div className="eyebrow">September Sprint</div><h2>90h feasible capacity</h2><p>18 working days · 18h buffer · maximum 7 subtasks/day</p></div><div className="sprint-kpis"><div><strong>{done}/{items.length}</strong><span>subtasks shipped</span></div><div><strong>{Math.round(done/Math.max(items.length,1)*100)}%</strong><span>closure</span></div></div></div><div className="sprint-toolbar"><div><strong>Sprint Gantt</strong><span>Task-level allocation across September</span></div></div><div className="gantt"><div className="gantt-head"><div>Task</div><div className="timeline-head">{Array.from({length:30},(_,i)=><span key={i}>{i+1}</span>)}</div></div>{tasks.map(t=>{const st=date(t.startDate),et=date(t.eta),left=((st-start)/span)*100,width=Math.max(.8,((et-st+86400000)/span)*100);return <button className="gantt-row" key={t.id} onClick={()=>{const s=items.find(x=>x.taskId===t.id);if(s)setSelected(s)}}><div><strong>{t.id}</strong><span>{t.title}</span></div><div className="timeline"><i style={{left:`${left}%`,width:`${width}%`}} title={`${fmt(t.startDate)} - ${fmt(t.eta)}`}></i></div></button>})}</div><div className="sprint-projects">{data.projects.map(p=>{const ss=items.filter(s=>s.project?.id===p.id),d=ss.filter(s=>s.status==='shipped').length;return <div key={p.id}><span>{p.name}</span><strong>{d}/{ss.length}</strong></div>})}</div></section>}
function MasterView({data,items,search,setSearch,setSelected,openAdd}){const [openProjects,setOpenProjects]=useState({}),[openTasks,setOpenTasks]=useState({});const q=search.trim().toLowerCase();const matches=x=>!q||[x?.title,x?.name,x?.description,x?.id].some(v=>String(v||'').toLowerCase().includes(q));return <section><div className="section-head"><div><div className="eyebrow">Source of truth</div><h2>Master Data</h2></div><div className="master-count">8 projects · 48 tasks · 201 subtasks</div></div><div className="master-tools"><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, tasks, subtasks"/></div><div className="add-group"><button onClick={()=>openAdd({type:'Project'})}>+ Project</button><button onClick={()=>openAdd({type:'Task'})}>+ Task</button><button onClick={()=>openAdd({type:'Subtask'})}>+ Subtask</button></div></div><div className="master-table"><div className="master-header"><span>Project</span><span>Task</span><span>Subtask</span><span>Status</span><span>Priority</span><span>Plan for</span><span>Details</span></div>{data.projects.map(p=>{const tasks=data.tasks.filter(t=>t.projectId===p.id);const projectMatch=matches(p)||tasks.some(t=>matches(t)||items.some(s=>s.taskId===t.id&&matches(s)));if(q&&!projectMatch)return null;const po=!!openProjects[p.id]||!!q;return <div key={p.id} className="hierarchy-block"><button className="master-row project" onClick={()=>setOpenProjects(x=>({...x,[p.id]:!x[p.id]}))}><span><b>{po?'▾':'▸'}</b>{p.name}</span><span></span><span></span><span>{pretty(p.status)}</span><span></span><span>{p.startDate&&p.endDate?`${fmt(p.startDate)} - ${fmt(p.endDate)}`:'Flexible'}</span><span>{p.description}</span></button>{po&&tasks.map(t=>{const subs=data.subtasks.filter(s=>s.taskId===t.id);if(q&&!matches(t)&&!subs.some(matches))return null;const to=!!openTasks[t.id]||!!q;return <div key={t.id}><button className="master-row task" onClick={()=>setOpenTasks(x=>({...x,[t.id]:!x[t.id]}))}><span></span><span><b>{to?'▾':'▸'}</b>{t.id} · {t.title}</span><span></span><span>{pretty(t.status)}</span><span>{t.priority}</span><span>{t.plannedWeek||'Flexible'}</span><span>{t.description}</span></button>{to&&subs.map(s=><button className={`master-row subtask ${s.status==='blocked'?'blocked-row':''}`} key={s.id} onClick={()=>setSelected({...s,task:t,project:p})}><span></span><span></span><span><b>{s.id}</b> · {s.title}</span><span>{pretty(s.status)}</span><span>{s.priority||'Normal'}</span><span>{fmt(s.scheduledDate)}</span><span>{s.description}</span></button>)}</div>})}</div>})}</div></section>}
function Insights({data,items}){const shipped=items.filter(s=>s.status==='shipped').length,blocked=items.filter(s=>s.status==='blocked').length,carry=items.filter(s=>Number(s.carryForward)>0).length;const projects=data.projects.map(p=>{const ss=items.filter(s=>s.project?.id===p.id);return{p,done:ss.filter(s=>s.status==='shipped').length,total:ss.length};});return <section><div className="section-head"><div><div className="eyebrow">Patterns, not BI</div><h2>Insights</h2></div></div><div className="insight-grid"><Metric label="Closure rate" value={`${Math.round(shipped/Math.max(items.length,1)*100)}%`} note="subtasks shipped"/><Metric label="Carry-forward" value={carry} note="items carried"/><Metric label="Blocked" value={blocked} note="items blocked"/><Metric label="Open work" value={items.length-shipped} note="subtasks remaining"/></div><div className="insight-panel"><h3>Project progress</h3>{projects.map(x=><div className="progress-row" key={x.p.id}><span>{x.p.name}</span><div><i style={{width:`${x.total?x.done/x.total*100:0}%`}}></i></div><strong>{x.done}/{x.total}</strong></div>)}</div></section>}
function Metric({label,value,note}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Drawer({item,today,close,updateSub}){const setStatus=v=>updateSub(item.id,{status:v==='Shipped'?'shipped':v==='Blocked'?'blocked':v==='In Progress'?'in_progress':'planned',completedDate:v==='Shipped'?today:null});return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">Subtask</div><h2>{item.title}</h2><p className="muted">{item.task?.title||item.taskId}</p><Field label="Summary"><textarea defaultValue={item.description||''} onBlur={e=>updateSub(item.id,{description:e.target.value})}/></Field><div className="drawer-grid"><Field label="Status"><select value={pretty(item.status)} onChange={e=>setStatus(e.target.value)}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></Field><Field label="Priority"><select value={item.priority||'Normal'} onChange={e=>updateSub(item.id,{priority:e.target.value})}><option>Critical</option><option>High</option><option>Medium</option><option>Normal</option><option>Low</option></select></Field><Field label="Planned date"><input type="date" value={item.scheduledDate||''} onChange={e=>updateSub(item.id,{scheduledDate:e.target.value||null})}/></Field><Field label="Effort"><input type="number" min=".25" step=".25" value={item.effort||1} onChange={e=>updateSub(item.id,{effort:Number(e.target.value)})}/></Field></div><div className="drawer-meta"><span>Task</span><strong>{item.task?.id||item.taskId}</strong><span>Project</span><strong>{item.project?.name||''}</strong></div></aside></div>}
function Field({label,children}){return <div className="field"><label>{label}</label>{children}</div>}
function AddDrawer({data,context,close,addWork}){const [type,setType]=useState(context.type||'Subtask'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[projectId,setProjectId]=useState(context.projectId||data.projects[0]?.id||''),[taskId,setTaskId]=useState(context.taskId||data.tasks[0]?.id||''),[priority,setPriority]=useState('Normal'),[scheduledDate,setDate]=useState(context.scheduledDate||''),[effort,setEffort]=useState('1');const tasks=data.tasks.filter(t=>t.projectId===projectId);useEffect(()=>{if(type==='Subtask'&&!tasks.some(t=>t.id===taskId))setTaskId(tasks[0]?.id||'');},[projectId,type]);const submit=()=>{if(!title.trim())return;addWork({type,title:title.trim(),description,projectId,taskId,priority,scheduledDate,effort});};return <div className="drawer-backdrop" onClick={close}><aside className="drawer add-drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">Add</div><h2>Keep it simple.</h2><p className="muted">Wings fills the rest from context.</p><div className="segmented">{['Project','Task','Subtask'].map(x=><button key={x} className={type===x?'active':''} onClick={()=>setType(x)}>{x}</button>)}</div><Field label="What do you want to add?"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${type} name`}/></Field>{type!=='Project'&&<Field label={type==='Task'?'Project':'Task'}><select value={type==='Task'?projectId:taskId} onChange={e=>type==='Task'?setProjectId(e.target.value):setTaskId(e.target.value)}>{(type==='Task'?data.projects:tasks).map(x=><option key={x.id} value={x.id}>{type==='Task'?x.name:`${x.id} · ${x.title}`}</option>)}</select></Field>}{type==='Subtask'&&<Field label="Planned date"><input type="date" value={scheduledDate} onChange={e=>setDate(e.target.value)}/></Field>}{type!=='Project'&&<Field label="Priority"><select value={priority} onChange={e=>setPriority(e.target.value)}><option>Critical</option><option>High</option><option>Medium</option><option>Normal</option><option>Low</option></select></Field>}{type==='Subtask'&&<Field label="Effort"><input type="number" min=".25" step=".25" value={effort} onChange={e=>setEffort(e.target.value)}/></Field>}<Field label="Optional description"><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add only if useful"/></Field><button className="primary full" onClick={submit}>Add {type}</button></aside></div>}
createRoot(document.getElementById('root')).render(<App/>);
