import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {loadSeed} from './seed';
import './styles.css';

const seed=loadSeed();
const today='2026-09-10';
const key='wings-master-v1';
const priorities={Critical:4,High:3,Normal:2,Low:1};
const normStatus=s=>String(s||'').toLowerCase().replace(/\s+/g,'_');
const pretty=s=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
function initial(){const saved=localStorage.getItem(key);if(saved)try{return JSON.parse(saved)}catch{};return {projects:seed.projects,tasks:seed.tasks.map(t=>({...t,status:normStatus(t.status),priority:t.priority||'Normal'})),subtasks:seed.subtasks.map(s=>({...s,status:normStatus(s.status),priority:'Normal',effort:1,carryForward:0}))}}
function dateLabel(d){if(!d)return 'Unscheduled';const x=new Date(d+'T00:00:00');return x.toLocaleDateString('en-IN',{day:'numeric',month:'short'})}
function App(){
 const [data,setData]=useState(initial); const [view,setView]=useState('Day'); const [search,setSearch]=useState(''); const [expanded,setExpanded]=useState({}); const [selected,setSelected]=useState(null); const [toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem(key,JSON.stringify(data)),[data]);
 const projectBy=useMemo(()=>Object.fromEntries(data.projects.map(p=>[p.id,p])),[data.projects]);
 const taskBy=useMemo(()=>Object.fromEntries(data.tasks.map(t=>[t.id,t])),[data.tasks]);
 const enriched=useMemo(()=>data.subtasks.map(s=>({...s,task:taskBy[s.taskId],project:projectBy[taskBy[s.taskId]?.projectId]})),[data,taskBy,projectBy]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return enriched;return enriched.filter(s=>[s.title,s.description,s.task?.title,s.project?.name].some(v=>String(v||'').toLowerCase().includes(q)))},[enriched,search]);
 const updateSub=(id,patch)=>{setData(d=>({...d,subtasks:d.subtasks.map(s=>s.id===id?{...s,...patch}:s)}));setToast('Updated');setTimeout(()=>setToast(''),1200)};
 const addSub=()=>{const title=prompt('What do you want to add?');if(!title)return;let task=data.tasks.find(t=>title.toLowerCase().includes(t.id.toLowerCase()))||data.tasks[0];const id='WNG-'+Date.now();setData(d=>({...d,subtasks:[...d.subtasks,{id,taskId:task.id,title,description:'',status:'planned',priority:'Normal',effort:1,carryForward:0,scheduledDate:today}]}));setToast('Subtask added');setTimeout(()=>setToast(''),1200)};
 const plan=useMemo(()=>{const candidates=enriched.filter(s=>s.status!=='shipped'&&(!s.scheduledDate||s.scheduledDate<=today));return candidates.sort((a,b)=>{const ap=priorities[a.priority]||2,bp=priorities[b.priority]||2;const ai=a.status==='in_progress'?1:0,bi=b.status==='in_progress'?1:0;const ac=Number(a.carryForward||0),bc=Number(b.carryForward||0);return (bp+bi+bc)-(ap+ai+ac)}).slice(0,7)},[enriched]);
 const dayGroups={Backlog:visible.filter(s=>!s.scheduledDate&&s.status!=='shipped'),Planned:plan,InProgress:visible.filter(s=>s.status==='in_progress'),Shipped:visible.filter(s=>s.status==='shipped'&&s.completedDate===today)};
 const toggle=k=>setExpanded(e=>({...e,[k]:!e[k]}));
 const projectStats=p=>{const ts=data.tasks.filter(t=>t.projectId===p.id), ids=new Set(ts.map(t=>t.id)),ss=data.subtasks.filter(s=>ids.has(s.taskId));return {tasks:ts.length,subs:ss.length,done:ss.filter(s=>s.status==='shipped').length,pct:ss.length?Math.round(ss.filter(s=>s.status==='shipped').length/ss.length*100):0}};
 return <div className="app">
  <aside><div className="brand"><span className="mark">W</span><span>Wings</span></div><nav>{['Day','Week','Sprint','Master Data','Insights'].map(v=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}>{v}</button>)}</nav><div className="side-foot"><div className="capacity"><span>September</span><strong>90h</strong><small>feasible capacity</small></div><div className="hint">Master data stays complete.<br/>Plans stay small.</div></div></aside>
  <main><header><div><div className="eyebrow">Chief of Staff</div><h1>{view==='Day'?'In focus today: FDE Collection':view}</h1></div><div className="header-actions"><div className="today"><span>Today</span><strong>10 Sep 2026</strong></div><button className="primary" onClick={addSub}>+ Add</button></div></header>
   <div className="toolbar"><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, tasks, subtasks"/></div><span className="green-badge">Planning agent · deterministic</span></div>
   {view==='Day'&&<Day groups={dayGroups} updateSub={updateSub} selected={selected} setSelected={setSelected} plan={plan} />}
   {view==='Week'&&<Week enriched={enriched} today={today} updateSub={updateSub}/>} 
   {view==='Sprint'&&<Sprint data={data} projectStats={projectStats}/>} 
   {view==='Master Data'&&<Master data={data} expanded={expanded} toggle={toggle} selected={selected} setSelected={setSelected} search={search}/>} 
   {view==='Insights'&&<Insights data={data} enriched={enriched}/>} 
  </main>
  {selected&&<Drawer item={selected} data={data} close={()=>setSelected(null)} updateSub={updateSub}/>} {toast&&<div className="toast">{toast}</div>}
 </div>
}
function Card({s,updateSub,setSelected}){return <article className={'card '+(s.status==='blocked'?'blocked':'')} onClick={()=>setSelected(s)}><div className="card-top"><span className="priority">{s.priority||'Normal'}</span><span className="date">{dateLabel(s.scheduledDate)}</span></div><h3>{s.title}</h3><p>{s.project?.name||''} · {s.task?.title||''}</p><div className="card-bottom"><span>{Number(s.effort||1).toFixed(1)}h</span><select value={pretty(s.status)} onClick={e=>e.stopPropagation()} onChange={e=>updateSub(s.id,{status:normStatus(e.target.value),completedDate:e.target.value==='Shipped'?today:null})}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></div></article>}
function Day({groups,updateSub,setSelected,plan}){return <section><div className="agent"><div className="agent-icon">✦</div><div><strong>Today is curated around closure</strong><p>{plan.length} subtasks selected within the 7h working limit. Priority, carry-forward, current progress and dates are driving the recommendation.</p></div><span className="agent-badge">Why this plan</span></div><div className="kanban">{Object.entries(groups).map(([name,items])=><div className="lane" key={name}><div className="lane-head"><span>{name}</span><b>{items.length}</b></div>{items.slice(0,12).map(s=><Card key={s.id} s={s} updateSub={updateSub} setSelected={setSelected}/>)}{!items.length&&<div className="empty">Nothing here</div>}</div>)}</div></section>}
function Week({enriched,today,updateSub}){const days=['Mon','Tue','Wed','Thu','Fri'];return <section><div className="section-title"><div><div className="eyebrow">Week of 7 Sep</div><h2>Keep the week moving</h2></div><div className="week-nav">‹ <strong>This week</strong> ›</div></div><div className="week-grid">{days.map((d,i)=>{const date='2026-09-'+String(7+i).padStart(2,'0');const items=enriched.filter(s=>s.scheduledDate===date);return <div className={'day '+(date===today?'now':'')} key={d}><div className="day-label"><span>{d}</span><b>{dateLabel(date)}</b></div>{items.slice(0,8).map(s=><div className="mini" key={s.id}><span className={'dot '+s.status}></span><span>{s.title}</span></div>)}</div>})}</div></section>}
function Sprint({data,projectStats}){const total=data.subtasks.length,done=data.subtasks.filter(s=>s.status==='shipped').length;return <section><div className="hero-stat"><div><div className="eyebrow">September Sprint</div><h2>90h feasible capacity</h2><p>18 working days · 18h buffer · maximum 7 subtasks per day</p></div><div className="ring"><strong>{Math.round(done/Math.max(total,1)*100)}%</strong><span>closed</span></div></div><div className="project-list">{data.projects.map(p=>{const x=projectStats(p);return <div className="project-row" key={p.id}><div><strong>{p.name}</strong><span>{p.tag}</span></div><div className="bar"><i style={{width:x.pct+'%'}}/></div><div className="nums"><b>{x.done}/{x.subs}</b><span>{x.tasks} tasks</span></div></div>})}</div></section>}
function Master({data,expanded,toggle,setSelected,search}){return <section><div className="section-title"><div><div className="eyebrow">Source of truth</div><h2>Master Data</h2></div><span>{data.projects.length} projects · {data.tasks.length} tasks · {data.subtasks.length} subtasks</span></div><div className="master"><div className="master-head"><span>Project</span><span>Task</span><span>Subtask</span><span>Status</span><span>Priority</span><span>Plan for</span><span>Details</span></div>{data.projects.map(p=>{const ts=data.tasks.filter(t=>t.projectId===p.id);const open=expanded[p.id]||!!search;return <div key={p.id}><button className="master-project" onClick={()=>toggle(p.id)}><span>▸ {p.name}</span><span></span><span></span><span>{pretty(p.status)}</span><span>-</span><span>{dateLabel(p.start)} - {dateLabel(p.end)}</span><span>{p.description}</span></button>{open&&ts.map(t=>{const to=expanded[t.id]||!!search;const ss=data.subtasks.filter(s=>s.taskId===t.id);return <div key={t.id}><button className="master-task" onClick={()=>toggle(t.id)}><span></span><span>▸ {t.title}</span><span></span><span>{pretty(t.status)}</span><span>{t.priority}</span><span>{t.plannedWeek||'Flexible'}</span><span>{t.description}</span></button>{to&&ss.map(s=><button className="master-sub" key={s.id} onClick={()=>setSelected(s)}><span></span><span></span><span>{s.title}</span><span>{pretty(s.status)}</span><span>{s.priority||'Normal'}</span><span>{dateLabel(s.scheduledDate)}</span><span>{s.description||'Open detail'}</span></button>)}</div>})}</div>})}</div></section>}
function Insights({data,enriched}){const shipped=enriched.filter(s=>s.status==='shipped').length,blocked=enriched.filter(s=>s.status==='blocked').length,carry=enriched.filter(s=>Number(s.carryForward)>0).length;return <section><div className="section-title"><div><div className="eyebrow">Patterns, not BI</div><h2>Insights</h2></div></div><div className="insight-grid"><div><span>Closure rate</span><strong>{Math.round(shipped/Math.max(enriched.length,1)*100)}%</strong><small>subtasks shipped</small></div><div><span>Carry-forward</span><strong>{carry}</strong><small>items needing attention</small></div><div><span>Blocked</span><strong>{blocked}</strong><small>items currently blocked</small></div><div><span>Active work</span><strong>{enriched.filter(s=>s.status!=='shipped').length}</strong><small>open subtasks</small></div></div><div className="insight-note"><strong>Chief of Staff readout</strong><p>Wings keeps the master database complete while surfacing only the work that can realistically move today. Repeated carry-forward, approaching dates and blocked dependencies should rise in priority automatically.</p></div></section>}
function Drawer({item,close,updateSub}){return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="eyebrow">Subtask</div><h2>{item.title}</h2><p className="drawer-muted">{item.task?.title||item.taskId}</p><label>Summary</label><textarea defaultValue={item.description||''}/><div className="drawer-grid"><div><label>Status</label><select value={pretty(item.status)} onChange={e=>updateSub(item.id,{status:normStatus(e.target.value)})}><option>Planned</option><option>In Progress</option><option>Blocked</option><option>Shipped</option></select></div><div><label>Priority</label><select value={item.priority||'Normal'} onChange={e=>updateSub(item.id,{priority:e.target.value})}><option>Critical</option><option>High</option><option>Normal</option><option>Low</option></select></div><div><label>Planned date</label><input type="date" defaultValue={item.scheduledDate||''} onChange={e=>updateSub(item.id,{scheduledDate:e.target.value})}/></div><div><label>Effort</label><input type="number" min="0.25" step="0.25" defaultValue={item.effort||1} onChange={e=>updateSub(item.id,{effort:Number(e.target.value)})}/></div></div></aside></div>}

createRoot(document.getElementById('root')).render(<App/>);
